/*
============================================================
 AlphaInvest AI
 Script: 10_audit_operation_tables.sql

 Propósito:
 Crear las tablas necesarias para auditoría,
 seguridad, registro de errores, notificaciones,
 trabajos programados y control operativo de procesos.

 Dependencias:
 - 01_extensions.sql
 - 02_schemas.sql
 - 03_auth_tables.sql

 Esquemas:
 - audit
 - operation
============================================================
*/

BEGIN;

/*
============================================================
 1. TABLA: audit.registros_auditoria
============================================================
*/

CREATE TABLE IF NOT EXISTS audit.registros_auditoria
(
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_registros_auditoria
        PRIMARY KEY,

    usuario_id UUID NULL,

    esquema_entidad VARCHAR(63) NOT NULL,

    nombre_entidad VARCHAR(100) NOT NULL,

    registro_id VARCHAR(150) NULL,

    accion VARCHAR(30) NOT NULL,

    valores_anteriores JSONB NULL,

    valores_nuevos JSONB NULL,

    campos_modificados JSONB NULL,

    direccion_ip INET NULL,

    agente_usuario TEXT NULL,

    origen VARCHAR(50) NOT NULL
        DEFAULT 'APLICACION',

    identificador_solicitud VARCHAR(150) NULL,

    fecha_evento TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_registros_auditoria_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES app_auth.usuarios (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT ck_registros_auditoria_esquema
        CHECK
        (
            LENGTH(TRIM(esquema_entidad)) > 0
        ),

    CONSTRAINT ck_registros_auditoria_entidad
        CHECK
        (
            LENGTH(TRIM(nombre_entidad)) > 0
        ),

    CONSTRAINT ck_registros_auditoria_registro
        CHECK
        (
            registro_id IS NULL
            OR LENGTH(TRIM(registro_id)) > 0
        ),

    CONSTRAINT ck_registros_auditoria_accion
        CHECK
        (
            accion IN
            (
                'INSERT',
                'UPDATE',
                'DELETE',
                'LOGIN',
                'LOGOUT',
                'LECTURA',
                'EXPORTACION',
                'EJECUCION',
                'OTRA'
            )
        ),

    CONSTRAINT ck_registros_auditoria_valores_anteriores
        CHECK
        (
            valores_anteriores IS NULL
            OR jsonb_typeof(valores_anteriores) = 'object'
        ),

    CONSTRAINT ck_registros_auditoria_valores_nuevos
        CHECK
        (
            valores_nuevos IS NULL
            OR jsonb_typeof(valores_nuevos) = 'object'
        ),

    CONSTRAINT ck_registros_auditoria_campos_modificados
        CHECK
        (
            campos_modificados IS NULL
            OR jsonb_typeof(campos_modificados) = 'array'
        ),

    CONSTRAINT ck_registros_auditoria_origen
        CHECK
        (
            origen IN
            (
                'APLICACION',
                'BASE_DATOS',
                'API',
                'TRABAJO_PROGRAMADO',
                'ADMINISTRACION',
                'SISTEMA'
            )
        ),

    CONSTRAINT ck_registros_auditoria_identificador_solicitud
        CHECK
        (
            identificador_solicitud IS NULL
            OR LENGTH(TRIM(identificador_solicitud)) > 0
        ),

    CONSTRAINT ck_registros_auditoria_contenido
        CHECK
        (
            accion NOT IN ('INSERT', 'UPDATE', 'DELETE')
            OR registro_id IS NOT NULL
        )
);

COMMENT ON TABLE audit.registros_auditoria IS
'Historial de acciones relevantes realizadas sobre entidades y recursos de AlphaInvest AI.';

COMMENT ON COLUMN audit.registros_auditoria.usuario_id IS
'Usuario responsable de la acción, cuando pueda identificarse.';

COMMENT ON COLUMN audit.registros_auditoria.esquema_entidad IS
'Esquema PostgreSQL de la entidad afectada.';

COMMENT ON COLUMN audit.registros_auditoria.nombre_entidad IS
'Nombre de la tabla, recurso o entidad afectada.';

COMMENT ON COLUMN audit.registros_auditoria.registro_id IS
'Identificador textual del registro afectado.';

COMMENT ON COLUMN audit.registros_auditoria.accion IS
'Operación realizada sobre la entidad o recurso.';

COMMENT ON COLUMN audit.registros_auditoria.valores_anteriores IS
'Estado del registro antes de la modificación.';

COMMENT ON COLUMN audit.registros_auditoria.valores_nuevos IS
'Estado del registro después de la modificación.';

COMMENT ON COLUMN audit.registros_auditoria.campos_modificados IS
'Lista de campos modificados durante una actualización.';

COMMENT ON COLUMN audit.registros_auditoria.identificador_solicitud IS
'Identificador de correlación de la petición que originó el evento.';


/*
============================================================
 2. TABLA: audit.eventos_seguridad
============================================================
*/

CREATE TABLE IF NOT EXISTS audit.eventos_seguridad
(
    id UUID
        CONSTRAINT pk_eventos_seguridad
        PRIMARY KEY
        DEFAULT gen_random_uuid(),

    usuario_id UUID NULL,

    correo_intentado CITEXT NULL,

    tipo_evento VARCHAR(50) NOT NULL,

    severidad VARCHAR(20) NOT NULL
        DEFAULT 'BAJA',

    resultado VARCHAR(20) NOT NULL,

    direccion_ip INET NULL,

    agente_usuario TEXT NULL,

    recurso VARCHAR(200) NULL,

    descripcion TEXT NOT NULL,

    metadatos JSONB NULL,

    fecha_evento TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    revisado BOOLEAN NOT NULL
        DEFAULT FALSE,

    revisado_por UUID NULL,

    fecha_revision TIMESTAMPTZ NULL,

    observaciones_revision TEXT NULL,

    CONSTRAINT fk_eventos_seguridad_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES app_auth.usuarios (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_eventos_seguridad_revisor
        FOREIGN KEY (revisado_por)
        REFERENCES app_auth.usuarios (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT ck_eventos_seguridad_correo
        CHECK
        (
            correo_intentado IS NULL
            OR LENGTH(TRIM(correo_intentado::TEXT)) > 0
        ),

    CONSTRAINT ck_eventos_seguridad_tipo
        CHECK
        (
            tipo_evento IN
            (
                'LOGIN_EXITOSO',
                'LOGIN_FALLIDO',
                'USUARIO_BLOQUEADO',
                'TOKEN_INVALIDO',
                'TOKEN_EXPIRADO',
                'ACCESO_DENEGADO',
                'PERMISO_INSUFICIENTE',
                'CAMBIO_PASSWORD',
                'RECUPERACION_PASSWORD',
                'SESION_REVOCADA',
                'ACTIVIDAD_SOSPECHOSA',
                'OTRO'
            )
        ),

    CONSTRAINT ck_eventos_seguridad_severidad
        CHECK
        (
            severidad IN
            (
                'BAJA',
                'MEDIA',
                'ALTA',
                'CRITICA'
            )
        ),

    CONSTRAINT ck_eventos_seguridad_resultado
        CHECK
        (
            resultado IN
            (
                'EXITOSO',
                'FALLIDO',
                'BLOQUEADO',
                'DENEGADO',
                'INFORMATIVO'
            )
        ),

    CONSTRAINT ck_eventos_seguridad_recurso
        CHECK
        (
            recurso IS NULL
            OR LENGTH(TRIM(recurso)) > 0
        ),

    CONSTRAINT ck_eventos_seguridad_descripcion
        CHECK
        (
            LENGTH(TRIM(descripcion)) > 0
        ),

    CONSTRAINT ck_eventos_seguridad_metadatos
        CHECK
        (
            metadatos IS NULL
            OR jsonb_typeof(metadatos) = 'object'
        ),

    CONSTRAINT ck_eventos_seguridad_revision
        CHECK
        (
            (
                revisado = FALSE
                AND fecha_revision IS NULL
                AND revisado_por IS NULL
            )
            OR
            (
                revisado = TRUE
                AND fecha_revision IS NOT NULL
                AND revisado_por IS NOT NULL
            )
        ),

    CONSTRAINT ck_eventos_seguridad_fecha_revision
        CHECK
        (
            fecha_revision IS NULL
            OR fecha_revision >= fecha_evento
        ),

    CONSTRAINT ck_eventos_seguridad_observaciones
        CHECK
        (
            observaciones_revision IS NULL
            OR LENGTH(TRIM(observaciones_revision)) > 0
        )
);

COMMENT ON TABLE audit.eventos_seguridad IS
'Eventos relacionados con autenticación, autorización y actividad potencialmente sospechosa.';

COMMENT ON COLUMN audit.eventos_seguridad.correo_intentado IS
'Correo proporcionado en un intento de acceso, incluso si no corresponde a un usuario registrado.';

COMMENT ON COLUMN audit.eventos_seguridad.severidad IS
'Gravedad operativa y de seguridad asignada al evento.';

COMMENT ON COLUMN audit.eventos_seguridad.resultado IS
'Resultado de la operación relacionada con seguridad.';

COMMENT ON COLUMN audit.eventos_seguridad.revisado IS
'Indica si el evento fue revisado por un usuario autorizado.';


/*
============================================================
 3. TABLA: audit.errores_aplicacion
============================================================
*/

CREATE TABLE IF NOT EXISTS audit.errores_aplicacion
(
    id UUID
        CONSTRAINT pk_errores_aplicacion
        PRIMARY KEY
        DEFAULT gen_random_uuid(),

    usuario_id UUID NULL,

    servicio VARCHAR(100) NOT NULL,

    componente VARCHAR(150) NULL,

    entorno VARCHAR(30) NOT NULL,

    nivel VARCHAR(20) NOT NULL,

    codigo_error VARCHAR(100) NULL,

    tipo_excepcion VARCHAR(200) NULL,

    mensaje TEXT NOT NULL,

    detalle TEXT NULL,

    traza TEXT NULL,

    metodo_http VARCHAR(10) NULL,

    ruta_solicitud VARCHAR(500) NULL,

    codigo_http INTEGER NULL,

    identificador_solicitud VARCHAR(150) NULL,

    identificador_proceso VARCHAR(150) NULL,

    direccion_ip INET NULL,

    datos_contexto JSONB NULL,

    fecha_error TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    resuelto BOOLEAN NOT NULL
        DEFAULT FALSE,

    fecha_resolucion TIMESTAMPTZ NULL,

    resuelto_por UUID NULL,

    notas_resolucion TEXT NULL,

    CONSTRAINT fk_errores_aplicacion_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES app_auth.usuarios (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_errores_aplicacion_resuelto_por
        FOREIGN KEY (resuelto_por)
        REFERENCES app_auth.usuarios (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT ck_errores_aplicacion_servicio
        CHECK
        (
            LENGTH(TRIM(servicio)) > 0
        ),

    CONSTRAINT ck_errores_aplicacion_componente
        CHECK
        (
            componente IS NULL
            OR LENGTH(TRIM(componente)) > 0
        ),

    CONSTRAINT ck_errores_aplicacion_entorno
        CHECK
        (
            entorno IN
            (
                'LOCAL',
                'DESARROLLO',
                'PRUEBAS',
                'STAGING',
                'PRODUCCION'
            )
        ),

    CONSTRAINT ck_errores_aplicacion_nivel
        CHECK
        (
            nivel IN
            (
                'INFO',
                'WARNING',
                'ERROR',
                'CRITICAL'
            )
        ),

    CONSTRAINT ck_errores_aplicacion_codigo
        CHECK
        (
            codigo_error IS NULL
            OR LENGTH(TRIM(codigo_error)) > 0
        ),

    CONSTRAINT ck_errores_aplicacion_tipo_excepcion
        CHECK
        (
            tipo_excepcion IS NULL
            OR LENGTH(TRIM(tipo_excepcion)) > 0
        ),

    CONSTRAINT ck_errores_aplicacion_mensaje
        CHECK
        (
            LENGTH(TRIM(mensaje)) > 0
        ),

    CONSTRAINT ck_errores_aplicacion_metodo_http
        CHECK
        (
            metodo_http IS NULL
            OR metodo_http IN
            (
                'GET',
                'POST',
                'PUT',
                'PATCH',
                'DELETE',
                'OPTIONS',
                'HEAD'
            )
        ),

    CONSTRAINT ck_errores_aplicacion_ruta
        CHECK
        (
            ruta_solicitud IS NULL
            OR LENGTH(TRIM(ruta_solicitud)) > 0
        ),

    CONSTRAINT ck_errores_aplicacion_codigo_http
        CHECK
        (
            codigo_http IS NULL
            OR codigo_http BETWEEN 100 AND 599
        ),

    CONSTRAINT ck_errores_aplicacion_identificador_solicitud
        CHECK
        (
            identificador_solicitud IS NULL
            OR LENGTH(TRIM(identificador_solicitud)) > 0
        ),

    CONSTRAINT ck_errores_aplicacion_identificador_proceso
        CHECK
        (
            identificador_proceso IS NULL
            OR LENGTH(TRIM(identificador_proceso)) > 0
        ),

    CONSTRAINT ck_errores_aplicacion_contexto
        CHECK
        (
            datos_contexto IS NULL
            OR jsonb_typeof(datos_contexto) = 'object'
        ),

    CONSTRAINT ck_errores_aplicacion_resolucion
        CHECK
        (
            (
                resuelto = FALSE
                AND fecha_resolucion IS NULL
                AND resuelto_por IS NULL
            )
            OR
            (
                resuelto = TRUE
                AND fecha_resolucion IS NOT NULL
                AND resuelto_por IS NOT NULL
            )
        ),

    CONSTRAINT ck_errores_aplicacion_fecha_resolucion
        CHECK
        (
            fecha_resolucion IS NULL
            OR fecha_resolucion >= fecha_error
        ),

    CONSTRAINT ck_errores_aplicacion_notas
        CHECK
        (
            notas_resolucion IS NULL
            OR LENGTH(TRIM(notas_resolucion)) > 0
        )
);

COMMENT ON TABLE audit.errores_aplicacion IS
'Registro centralizado de errores y excepciones ocurridos en los servicios de AlphaInvest AI.';

COMMENT ON COLUMN audit.errores_aplicacion.servicio IS
'Servicio que reportó el error, por ejemplo API, MOTOR_IA o MARKET_SERVICE.';

COMMENT ON COLUMN audit.errores_aplicacion.nivel IS
'Nivel de gravedad técnica del evento registrado.';

COMMENT ON COLUMN audit.errores_aplicacion.identificador_solicitud IS
'Identificador utilizado para correlacionar el error con una petición del usuario.';

COMMENT ON COLUMN audit.errores_aplicacion.datos_contexto IS
'Información técnica adicional necesaria para diagnosticar el error.';

COMMENT ON COLUMN audit.errores_aplicacion.resuelto IS
'Indica si el error fue investigado y marcado como resuelto.';


/*
============================================================
 4. TABLA: operation.notificaciones
============================================================
*/

CREATE TABLE IF NOT EXISTS operation.notificaciones
(
    id UUID
        CONSTRAINT pk_notificaciones
        PRIMARY KEY
        DEFAULT gen_random_uuid(),

    usuario_id UUID NOT NULL,

    tipo VARCHAR(40) NOT NULL,

    canal VARCHAR(20) NOT NULL,

    titulo VARCHAR(200) NOT NULL,

    mensaje TEXT NOT NULL,

    prioridad VARCHAR(20) NOT NULL
        DEFAULT 'NORMAL',

    estado VARCHAR(30) NOT NULL
        DEFAULT 'PENDIENTE',

    datos JSONB NULL,

    fecha_creacion TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    fecha_programada TIMESTAMPTZ NULL,

    fecha_envio TIMESTAMPTZ NULL,

    fecha_lectura TIMESTAMPTZ NULL,

    intentos_envio INTEGER NOT NULL
        DEFAULT 0,

    ultimo_error TEXT NULL,

    referencia_tipo VARCHAR(50) NULL,

    referencia_id VARCHAR(150) NULL,

    CONSTRAINT fk_notificaciones_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES app_auth.usuarios (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT ck_notificaciones_tipo
        CHECK
        (
            tipo IN
            (
                'SISTEMA',
                'SEGURIDAD',
                'ALERTA_PRECIO',
                'SIMULACION',
                'ANALISIS_IA',
                'RECOMENDACION',
                'PORTAFOLIO',
                'MANTENIMIENTO',
                'OTRA'
            )
        ),

    CONSTRAINT ck_notificaciones_canal
        CHECK
        (
            canal IN
            (
                'APLICACION',
                'CORREO',
                'PUSH'
            )
        ),

    CONSTRAINT ck_notificaciones_titulo
        CHECK
        (
            LENGTH(TRIM(titulo)) > 0
        ),

    CONSTRAINT ck_notificaciones_mensaje
        CHECK
        (
            LENGTH(TRIM(mensaje)) > 0
        ),

    CONSTRAINT ck_notificaciones_prioridad
        CHECK
        (
            prioridad IN
            (
                'BAJA',
                'NORMAL',
                'ALTA',
                'URGENTE'
            )
        ),

    CONSTRAINT ck_notificaciones_estado
        CHECK
        (
            estado IN
            (
                'PENDIENTE',
                'PROGRAMADA',
                'ENVIANDO',
                'ENVIADA',
                'FALLIDA',
                'CANCELADA'
            )
        ),

    CONSTRAINT ck_notificaciones_datos
        CHECK
        (
            datos IS NULL
            OR jsonb_typeof(datos) = 'object'
        ),

    CONSTRAINT ck_notificaciones_fecha_programada
        CHECK
        (
            fecha_programada IS NULL
            OR fecha_programada >= fecha_creacion
        ),

    CONSTRAINT ck_notificaciones_fecha_envio
        CHECK
        (
            fecha_envio IS NULL
            OR fecha_envio >= fecha_creacion
        ),

    CONSTRAINT ck_notificaciones_fecha_lectura
        CHECK
        (
            fecha_lectura IS NULL
            OR
            (
                fecha_envio IS NOT NULL
                AND fecha_lectura >= fecha_envio
            )
        ),

    CONSTRAINT ck_notificaciones_intentos
        CHECK
        (
            intentos_envio >= 0
        ),

    CONSTRAINT ck_notificaciones_estado_programada
        CHECK
        (
            estado <> 'PROGRAMADA'
            OR fecha_programada IS NOT NULL
        ),

    CONSTRAINT ck_notificaciones_estado_enviada
        CHECK
        (
            estado <> 'ENVIADA'
            OR fecha_envio IS NOT NULL
        ),

    CONSTRAINT ck_notificaciones_estado_fallida
        CHECK
        (
            estado <> 'FALLIDA'
            OR NULLIF(TRIM(ultimo_error), '') IS NOT NULL
        ),

    CONSTRAINT ck_notificaciones_referencia
        CHECK
        (
            (
                referencia_tipo IS NULL
                AND referencia_id IS NULL
            )
            OR
            (
                referencia_tipo IS NOT NULL
                AND referencia_id IS NOT NULL
                AND LENGTH(TRIM(referencia_tipo)) > 0
                AND LENGTH(TRIM(referencia_id)) > 0
            )
        )
);

COMMENT ON TABLE operation.notificaciones IS
'Notificaciones generadas para los usuarios de AlphaInvest AI.';

COMMENT ON COLUMN operation.notificaciones.canal IS
'Medio mediante el cual debe enviarse la notificación.';

COMMENT ON COLUMN operation.notificaciones.estado IS
'Estado operativo del proceso de envío.';

COMMENT ON COLUMN operation.notificaciones.datos IS
'Información estructurada utilizada por la interfaz o plantilla de notificación.';

COMMENT ON COLUMN operation.notificaciones.referencia_tipo IS
'Tipo de entidad relacionada, por ejemplo RECOMENDACION o SIMULACION.';

COMMENT ON COLUMN operation.notificaciones.referencia_id IS
'Identificador de la entidad relacionada con la notificación.';


/*
============================================================
 5. TABLA: operation.trabajos_programados
============================================================
*/

CREATE TABLE IF NOT EXISTS operation.trabajos_programados
(
    id UUID
        CONSTRAINT pk_trabajos_programados
        PRIMARY KEY
        DEFAULT gen_random_uuid(),

    codigo VARCHAR(100) NOT NULL,

    nombre VARCHAR(150) NOT NULL,

    descripcion TEXT NULL,

    tipo VARCHAR(40) NOT NULL,

    expresion_cron VARCHAR(100) NULL,

    intervalo_segundos INTEGER NULL,

    zona_horaria VARCHAR(80) NOT NULL
        DEFAULT 'UTC',

    parametros JSONB NULL,

    activo BOOLEAN NOT NULL
        DEFAULT TRUE,

    permite_concurrencia BOOLEAN NOT NULL
        DEFAULT FALSE,

    tiempo_maximo_segundos INTEGER NULL,

    maximo_reintentos INTEGER NOT NULL
        DEFAULT 0,

    siguiente_ejecucion TIMESTAMPTZ NULL,

    ultima_ejecucion TIMESTAMPTZ NULL,

    creado_por UUID NULL,

    fecha_creacion TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    fecha_actualizacion TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_trabajos_programados_creado_por
        FOREIGN KEY (creado_por)
        REFERENCES app_auth.usuarios (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT uq_trabajos_programados_codigo
        UNIQUE (codigo),

    CONSTRAINT ck_trabajos_programados_codigo
        CHECK
        (
            LENGTH(TRIM(codigo)) > 0
        ),

    CONSTRAINT ck_trabajos_programados_nombre
        CHECK
        (
            LENGTH(TRIM(nombre)) > 0
        ),

    CONSTRAINT ck_trabajos_programados_descripcion
        CHECK
        (
            descripcion IS NULL
            OR LENGTH(TRIM(descripcion)) > 0
        ),

    CONSTRAINT ck_trabajos_programados_tipo
        CHECK
        (
            tipo IN
            (
                'CRON',
                'INTERVALO',
                'MANUAL'
            )
        ),

    CONSTRAINT ck_trabajos_programados_programacion
        CHECK
        (
            (
                tipo = 'CRON'
                AND expresion_cron IS NOT NULL
                AND intervalo_segundos IS NULL
            )
            OR
            (
                tipo = 'INTERVALO'
                AND expresion_cron IS NULL
                AND intervalo_segundos IS NOT NULL
            )
            OR
            (
                tipo = 'MANUAL'
                AND expresion_cron IS NULL
                AND intervalo_segundos IS NULL
            )
        ),

    CONSTRAINT ck_trabajos_programados_cron
        CHECK
        (
            expresion_cron IS NULL
            OR LENGTH(TRIM(expresion_cron)) > 0
        ),

    CONSTRAINT ck_trabajos_programados_intervalo
        CHECK
        (
            intervalo_segundos IS NULL
            OR intervalo_segundos > 0
        ),

    CONSTRAINT ck_trabajos_programados_zona_horaria
        CHECK
        (
            LENGTH(TRIM(zona_horaria)) > 0
        ),

    CONSTRAINT ck_trabajos_programados_parametros
        CHECK
        (
            parametros IS NULL
            OR jsonb_typeof(parametros) = 'object'
        ),

    CONSTRAINT ck_trabajos_programados_tiempo_maximo
        CHECK
        (
            tiempo_maximo_segundos IS NULL
            OR tiempo_maximo_segundos > 0
        ),

    CONSTRAINT ck_trabajos_programados_reintentos
        CHECK
        (
            maximo_reintentos BETWEEN 0 AND 100
        ),

    CONSTRAINT ck_trabajos_programados_fechas
        CHECK
        (
            ultima_ejecucion IS NULL
            OR siguiente_ejecucion IS NULL
            OR siguiente_ejecucion >= ultima_ejecucion
        )
);

COMMENT ON TABLE operation.trabajos_programados IS
'Definición de procesos automáticos o manuales ejecutados por los servicios de AlphaInvest AI.';

COMMENT ON COLUMN operation.trabajos_programados.codigo IS
'Código técnico único utilizado para identificar el trabajo.';

COMMENT ON COLUMN operation.trabajos_programados.tipo IS
'Forma de ejecución del trabajo: CRON, INTERVALO o MANUAL.';

COMMENT ON COLUMN operation.trabajos_programados.expresion_cron IS
'Expresión de programación utilizada por trabajos de tipo CRON.';

COMMENT ON COLUMN operation.trabajos_programados.intervalo_segundos IS
'Frecuencia de ejecución para trabajos de tipo INTERVALO.';

COMMENT ON COLUMN operation.trabajos_programados.permite_concurrencia IS
'Indica si pueden existir varias ejecuciones simultáneas del mismo trabajo.';

COMMENT ON COLUMN operation.trabajos_programados.tiempo_maximo_segundos IS
'Tiempo máximo permitido para una ejecución antes de considerarla agotada.';


/*
============================================================
 6. TABLA: operation.ejecuciones_trabajo
============================================================
*/

CREATE TABLE IF NOT EXISTS operation.ejecuciones_trabajo
(
    id UUID
        CONSTRAINT pk_ejecuciones_trabajo
        PRIMARY KEY
        DEFAULT gen_random_uuid(),

    trabajo_id UUID NOT NULL,

    estado VARCHAR(30) NOT NULL
        DEFAULT 'PENDIENTE',

    numero_intento INTEGER NOT NULL
        DEFAULT 1,

    disparador VARCHAR(30) NOT NULL,

    solicitado_por UUID NULL,

    identificador_proceso VARCHAR(150) NULL,

    fecha_programada TIMESTAMPTZ NULL,

    fecha_solicitud TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    fecha_inicio TIMESTAMPTZ NULL,

    fecha_fin TIMESTAMPTZ NULL,

    progreso NUMERIC(7,4) NOT NULL
        DEFAULT 0,

    registros_procesados BIGINT NOT NULL
        DEFAULT 0,

    registros_exitosos BIGINT NOT NULL
        DEFAULT 0,

    registros_fallidos BIGINT NOT NULL
        DEFAULT 0,

    resultado JSONB NULL,

    mensaje_error TEXT NULL,

    CONSTRAINT fk_ejecuciones_trabajo_trabajo
        FOREIGN KEY (trabajo_id)
        REFERENCES operation.trabajos_programados (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_ejecuciones_trabajo_solicitado_por
        FOREIGN KEY (solicitado_por)
        REFERENCES app_auth.usuarios (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT uq_ejecuciones_trabajo_proceso
        UNIQUE (identificador_proceso),

    CONSTRAINT ck_ejecuciones_trabajo_estado
        CHECK
        (
            estado IN
            (
                'PENDIENTE',
                'EJECUTANDO',
                'COMPLETADA',
                'FALLIDA',
                'CANCELADA',
                'OMITIDA'
            )
        ),

    CONSTRAINT ck_ejecuciones_trabajo_intento
        CHECK
        (
            numero_intento > 0
        ),

    CONSTRAINT ck_ejecuciones_trabajo_disparador
        CHECK
        (
            disparador IN
            (
                'PROGRAMADO',
                'MANUAL',
                'REINTENTO',
                'SISTEMA'
            )
        ),

    CONSTRAINT ck_ejecuciones_trabajo_identificador
        CHECK
        (
            identificador_proceso IS NULL
            OR LENGTH(TRIM(identificador_proceso)) > 0
        ),

    CONSTRAINT ck_ejecuciones_trabajo_fechas_inicio
        CHECK
        (
            fecha_inicio IS NULL
            OR fecha_inicio >= fecha_solicitud
        ),

    CONSTRAINT ck_ejecuciones_trabajo_fechas_fin
        CHECK
        (
            fecha_fin IS NULL
            OR
            (
                fecha_inicio IS NOT NULL
                AND fecha_fin >= fecha_inicio
            )
        ),

    CONSTRAINT ck_ejecuciones_trabajo_progreso
        CHECK
        (
            progreso BETWEEN 0 AND 100
        ),

    CONSTRAINT ck_ejecuciones_trabajo_registros
        CHECK
        (
            registros_procesados >= 0
            AND registros_exitosos >= 0
            AND registros_fallidos >= 0
        ),

    CONSTRAINT ck_ejecuciones_trabajo_conteo
        CHECK
        (
            registros_exitosos + registros_fallidos
            <= registros_procesados
        ),

    CONSTRAINT ck_ejecuciones_trabajo_resultado
        CHECK
        (
            resultado IS NULL
            OR jsonb_typeof(resultado) = 'object'
        ),

    CONSTRAINT ck_ejecuciones_trabajo_estado_inicio
        CHECK
        (
            estado = 'PENDIENTE'
            OR estado = 'OMITIDA'
            OR fecha_inicio IS NOT NULL
        ),

    CONSTRAINT ck_ejecuciones_trabajo_estado_fin
        CHECK
        (
            estado NOT IN
            (
                'COMPLETADA',
                'FALLIDA',
                'CANCELADA',
                'OMITIDA'
            )
            OR fecha_fin IS NOT NULL
        ),

    CONSTRAINT ck_ejecuciones_trabajo_completada
        CHECK
        (
            estado <> 'COMPLETADA'
            OR progreso = 100
        ),

    CONSTRAINT ck_ejecuciones_trabajo_fallida
        CHECK
        (
            estado <> 'FALLIDA'
            OR NULLIF(TRIM(mensaje_error), '') IS NOT NULL
        )
);

COMMENT ON TABLE operation.ejecuciones_trabajo IS
'Historial de ejecuciones de los trabajos definidos en el esquema operation.';

COMMENT ON COLUMN operation.ejecuciones_trabajo.numero_intento IS
'Número de intento de ejecución para el mismo procesamiento lógico.';

COMMENT ON COLUMN operation.ejecuciones_trabajo.disparador IS
'Origen que inició la ejecución del trabajo.';

COMMENT ON COLUMN operation.ejecuciones_trabajo.progreso IS
'Porcentaje de avance de la ejecución entre cero y cien.';

COMMENT ON COLUMN operation.ejecuciones_trabajo.resultado IS
'Resumen estructurado del resultado de la ejecución.';


/*
============================================================
 7. TABLA: operation.control_procesos
============================================================
*/

CREATE TABLE IF NOT EXISTS operation.control_procesos
(
    id UUID
        CONSTRAINT pk_control_procesos
        PRIMARY KEY
        DEFAULT gen_random_uuid(),

    tipo_proceso VARCHAR(50) NOT NULL,

    entidad_tipo VARCHAR(50) NULL,

    entidad_id VARCHAR(150) NULL,

    clave_bloqueo VARCHAR(200) NOT NULL,

    estado VARCHAR(30) NOT NULL
        DEFAULT 'ADQUIRIDO',

    propietario VARCHAR(150) NOT NULL,

    identificador_proceso VARCHAR(150) NOT NULL,

    fecha_adquisicion TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    fecha_expiracion TIMESTAMPTZ NOT NULL,

    fecha_liberacion TIMESTAMPTZ NULL,

    latido_actualizacion TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    metadatos JSONB NULL,

    CONSTRAINT uq_control_procesos_clave
        UNIQUE (clave_bloqueo),

    CONSTRAINT uq_control_procesos_identificador
        UNIQUE (identificador_proceso),

    CONSTRAINT ck_control_procesos_tipo
        CHECK
        (
            tipo_proceso IN
            (
                'SIMULACION',
                'ANALISIS_IA',
                'CARGA_MERCADO',
                'ENVIO_NOTIFICACION',
                'TRABAJO_PROGRAMADO',
                'MANTENIMIENTO',
                'OTRO'
            )
        ),

    CONSTRAINT ck_control_procesos_entidad
        CHECK
        (
            (
                entidad_tipo IS NULL
                AND entidad_id IS NULL
            )
            OR
            (
                entidad_tipo IS NOT NULL
                AND entidad_id IS NOT NULL
                AND LENGTH(TRIM(entidad_tipo)) > 0
                AND LENGTH(TRIM(entidad_id)) > 0
            )
        ),

    CONSTRAINT ck_control_procesos_clave
        CHECK
        (
            LENGTH(TRIM(clave_bloqueo)) > 0
        ),

    CONSTRAINT ck_control_procesos_estado
        CHECK
        (
            estado IN
            (
                'ADQUIRIDO',
                'LIBERADO',
                'EXPIRADO',
                'CANCELADO'
            )
        ),

    CONSTRAINT ck_control_procesos_propietario
        CHECK
        (
            LENGTH(TRIM(propietario)) > 0
        ),

    CONSTRAINT ck_control_procesos_identificador
        CHECK
        (
            LENGTH(TRIM(identificador_proceso)) > 0
        ),

    CONSTRAINT ck_control_procesos_expiracion
        CHECK
        (
            fecha_expiracion > fecha_adquisicion
        ),

    CONSTRAINT ck_control_procesos_liberacion
        CHECK
        (
            fecha_liberacion IS NULL
            OR fecha_liberacion >= fecha_adquisicion
        ),

    CONSTRAINT ck_control_procesos_latido
        CHECK
        (
            latido_actualizacion >= fecha_adquisicion
        ),

    CONSTRAINT ck_control_procesos_estado_liberado
        CHECK
        (
            estado <> 'LIBERADO'
            OR fecha_liberacion IS NOT NULL
        ),

    CONSTRAINT ck_control_procesos_estado_adquirido
        CHECK
        (
            estado <> 'ADQUIRIDO'
            OR fecha_liberacion IS NULL
        ),

    CONSTRAINT ck_control_procesos_metadatos
        CHECK
        (
            metadatos IS NULL
            OR jsonb_typeof(metadatos) = 'object'
        )
);

COMMENT ON TABLE operation.control_procesos IS
'Mecanismo de control y bloqueo lógico para evitar procesamientos simultáneos incompatibles.';

COMMENT ON COLUMN operation.control_procesos.clave_bloqueo IS
'Clave única que representa el recurso o proceso bloqueado.';

COMMENT ON COLUMN operation.control_procesos.propietario IS
'Instancia, servicio o trabajador que adquirió el bloqueo.';

COMMENT ON COLUMN operation.control_procesos.fecha_expiracion IS
'Fecha límite después de la cual el bloqueo puede considerarse abandonado.';

COMMENT ON COLUMN operation.control_procesos.latido_actualizacion IS
'Última señal de actividad enviada por el proceso propietario.';

COMMENT ON COLUMN operation.control_procesos.metadatos IS
'Información adicional necesaria para supervisar el proceso.';


/*
============================================================
 8. CONFIRMACIÓN
============================================================
*/

COMMIT;