from enum import StrEnum


class UserStatus(StrEnum):
    PENDING_VERIFICATION = "PENDIENTE_VERIFICACION"
    ACTIVE = "ACTIVO"
    BLOCKED = "BLOQUEADO"
    INACTIVE = "INACTIVO"


class RoleName(StrEnum):
    ADMIN = "ADMINISTRADOR"
    ANALYST = "ANALISTA"
    INVESTOR = "INVERSIONISTA"
    OPERATOR = "OPERADOR"
    AUDITOR = "AUDITOR"


class SecurityEventType(StrEnum):
    LOGIN_SUCCESS = "LOGIN_EXITOSO"
    LOGIN_FAILED = "LOGIN_FALLIDO"
    USER_BLOCKED = "USUARIO_BLOQUEADO"
    INVALID_TOKEN = "TOKEN_INVALIDO"
    EXPIRED_TOKEN = "TOKEN_EXPIRADO"
    ACCESS_DENIED = "ACCESO_DENEGADO"
    INSUFFICIENT_PERMISSION = "PERMISO_INSUFICIENTE"
    SESSION_REVOKED = "SESION_REVOCADA"
